### ISSUE TITLE
Panic in autorest/adal/token.go

### ISSUE THREAD

**Issue by carlpett** [Azure/go-autorest#290]
I'm getting a panic in go-autorest when trying to use `NewAuthorizerFromEnvironment` ([source](https://github.com/Azure/azure-sdk-for-go/blob/cd93ccfe0395e70031704ca68f14606588eec120/services/keyvault/auth/auth.go#L31)) from the `keyvault/auth` package. This happens if I do not set up any environment variables before, so I would expect it to just fail with a 401.

It takes 30 seconds before it crashes, so I'm guessing there's some timeout somewhere which doesn't get aborted on auth failures?

**Versions**
go-autorest: v10.11.2
azure-sdk-for-go: v17.3.0

**Repro case**
```golang
package main

import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault"
	"github.com/Azure/azure-sdk-for-go/services/keyvault/auth"
)

func newKeyVaultClient() (keyvault.BaseClient, error) {
	var err error
	c := keyvault.New()
	c.Authorizer, err = auth.NewAuthorizerFromEnvironment()
	if err != nil {
		log.Printf("Failed to create Azure authorizer: %v\n", err)
		return c, err
	}

	return c, nil
}

type VaultKey struct {
	VaultURL string
	Name     string
	Version  string
}

func Encrypt(data string, key VaultKey) error {
	c, err := newKeyVaultClient()
	if err != nil {
		return err
	}
	p := keyvault.KeyOperationsParameters{Value: &data}

	// Crash here
	res, err := c.Encrypt(context.TODO(), key.VaultURL, key.Name, key.Version, p)
	log.Println(res)
	return err
}

func main() {
	log.Fatal(Encrypt("foo", VaultKey{
		VaultURL: "https://my-vault-url.vault.azure.net",
		Name:     "test-key",
		Version:  "a2a690a4fcc04166b739da342a912c90",
	}))
}
```

**Stack trace**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x825680]

goroutine 1 [running]:
github.com/Azure/go-autorest/autorest/adal.retry(0xd18f80, 0xc420205dd0, 0xc420214500, 0x0, 0x0, 0xc764b9)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/adal/token.go:887 +0x1a0
github.com/Azure/go-autorest/autorest/adal.(*ServicePrincipalToken).refreshInternal(0xc42019d200, 0xd21c00, 0xc420028178, 0xc60e96, 0x17, 0x0, 0x0)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/adal/token.go:814 +0x27f
github.com/Azure/go-autorest/autorest/adal.(*ServicePrincipalToken).EnsureFreshWithContext(0xc42019d200, 0xd21c00, 0xc420028178, 0x0, 0x0)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/adal/token.go:704 +0x1c8
github.com/Azure/go-autorest/autorest.(*BearerAuthorizer).WithAuthorization.func1.1(0xc420214300, 0xc4201bb050, 0x8466ba, 0xd19920)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/authorization.go:118 +0x100
github.com/Azure/go-autorest/autorest.PreparerFunc.Prepare(0xc4202463e0, 0xc420214300, 0xc4201bb098, 0x846647, 0xd19920)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/preparer.go:52 +0x30
github.com/Azure/go-autorest/autorest.WithNothing.func1.1(0xc420214300, 0x2, 0xd19920, 0xc420246400)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/preparer.go:93 +0x39
github.com/Azure/go-autorest/autorest.PreparerFunc.Prepare(0xc420246400, 0xc420214300, 0x2, 0xd19920, 0xc420246400)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/preparer.go:52 +0x30
github.com/Azure/go-autorest/autorest.Prepare(0xc420214300, 0xc4201bb300, 0x2, 0x2, 0x0, 0x0, 0xdf8475800)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/preparer.go:85 +0x8f
github.com/Azure/go-autorest/autorest.Client.Do(0xd180c0, 0xc420230470, 0xd18f60, 0xc420205da0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/client.go:207 +0x133
github.com/Azure/go-autorest/autorest.DoRetryForStatusCodes.func1.1(0xc420214300, 0xd19960, 0xc420075f40, 0x0)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/sender.go:225 +0x11e
github.com/Azure/go-autorest/autorest.SenderFunc.Do(0xc420075f40, 0xc420214300, 0xc4201bb760, 0x1, 0x1)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/sender.go:38 +0x30
github.com/Azure/go-autorest/autorest.SendWithSender(0xd198c0, 0xc4200ea600, 0xc420214300, 0xc4201bb760, 0x1, 0x1, 0x0, 0x0, 0xb226e0)
        /$GOPATH/src/github.com/Azure/go-autorest/autorest/sender.go:80 +0x75
github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault.BaseClient.EncryptSender(0xd180c0, 0xc420230470, 0xd18f60, 0xc420205da0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
        /$GOPATH/src/github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault/client.go:1085 +0x10c
github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault.BaseClient.Encrypt(0xd180c0, 0xc420230470, 0xd18f60, 0xc420205da0, 0x0, 0x0, 0xdf8475800, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
        /$GOPATH/src/github.com/Azure/azure-sdk-for-go/services/keyvault/2016-10-01/keyvault/client.go:1041 +0x2f9
main.Encrypt(0x70815b, 0x3, 0x712052, 0x21, 0x709592, 0x8, 0x71163b, 0x20, 0x0, 0x6659d8)
        /tmp/azure-auth-crash.go:37 +0x20a
main.main()
        /tmp/azure-auth-crash.go:43 +0x59
exit status 2
```

**Comment by jhendrixMSFT** [comment]
Panic doesn't repro on Windows but it does on Mac, investigating further...

**Comment by jhendrixMSFT** [comment]
Here's what I have so far.  Lack of environment vars means ```NewAuthorizerFromEnvironment``` will default to case number four which is MSI authentication; in this case the authorizer will attempt to connect to a locally-running server to obtain a token.  Since the server isn't running the TCP dialer fails to make a connection so ```sender.Do``` [here](https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L885) returns a nil response with a ```url.Error```; this error wraps a ```net.OpError```, and on Windows that wraps a ```os.SyscallError``` however on Mac it wraps a ```poll.TimeoutError```.  For Windows ```SyscallError.Temporary()``` returns ```false``` however on Mac ```TimeoutError.Temporary``` returns ```true``` (see [here](https://github.com/golang/go/blob/master/src/internal/poll/fd.go#L45)).  As a result, when running on Mac we think this is a temporary error and attempt to dereference a nil response.
I will fix the nil dereference however the rest is IMO a defect in the standard library.

**Comment by jhendrixMSFT** [comment]
No panic on Linux, must be specific to Mac.

**Comment by jhendrixMSFT** [comment]
This has been fixed in https://github.com/Azure/go-autorest/releases/tag/v10.11.3

**Comment by carlpett** [comment]
@jhendrixMSFT Hm, I'm actually on Linux, though, so definitely not Mac only. I'll see if it works better on Linux too with the fix

**Comment by carlpett** [comment]
With the fix applied I do not get a panic, but a timeout trying to reach the metadata endpoint (testing on my laptop, so expected that it cannot be reached)
